### ISSUE TITLE
Convert Lat/Lon to Address

### ISSUE THREAD

**Issue by kangaroooh** [robroooh/txt-mng#2]
Using OpenStreetMap API to convert Lat/Lon column in Data.Police.uk to convert to address

> Once you have saved the data in your local machine, try to reuse existing APIs to harmonize the two datasets. For example, the Data.Police.uk dataset contains Latitude (F5) and Longitude (F6) variables, while the hotel reviews dataset contains only the Hotel Address (F3). Use the Google’s Geocoding API (or any other free API OpenStreetMap.org) to convert addresses (like "1600 Amphitheatre Parkway, Mountain View, CA") into geographic coordinates (like latitude 37.423021 and longitude -122.083739).

**Comment by lbf4616** [comment]
I am working on this part.
